---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install docker dependencies
      apt:
        name: 
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Clone Node.js app repository
      git:
        repo: https://github.com/luisrom661/app-user-backend
        dest: /var/www/html/app-user-backend
    
    - name: Build Docker image
      command: docker build -t app-user-backend /var/www/html/app-user-backend
      
    - name: Run Docker container
      command: docker run -d -p 3000:3000 --name app-user-backend-container app-user-backend